# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A fun way to learn computer pogramming
email: viebel@gmail.com
description: A fun and interactive way to learn computer pogramming. With clojure and klipse.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://kids.klipse.tech/" # the base hostname & protocol for your site
author: Yehonathan Sharvit

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
