---
title: Klipse for Kids
email: viebel@gmail.com
author: hugocarreira
author_github: hugocarreira
description: |
  A fun way to learn computer programming
baseurl: "/"
paginate: 12
github:
  user: viebel
  repository: jekyll-materializecss
  url: http://hugocarreira.github.io/jekyll-materializecss/
  status: true
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
